### ISSUE TITLE
Subsequent spin ups from AMI limit Parsec's display resolutions

### ISSUE THREAD

**Issue by josiasteo** [keithvassallomt/parsec-aws-automation#1]
Hey there, This guide is the best of all the others I have come across so far!  It's extremely clear and does not leave out details.  And it works!

I have followed the guide including the optional scripts for snap and delete and spin up of instance by cli script.  I noticed that on the very first time which I manually created and launched the instance via AWS console, everything was fine.  Parsec could display all available resolutions without problems.  However, after I terminated the instance, and spun up a new one with the cli script, Parsec started behaving strangely.  It could only display 2 resolutions: 1368x768 and 1280x1024.  Any other resolution I tried to force Parsec to use (both by config file and choosing from the drop down list) would have no effect, and resolution would persist at either 1368x768 or 1280x1024.

I also noticed that in Parsec's Host settings, the output display changed from ".\\.Display1.\" to "Generic PnP Monitor".  Not sure if this is a symptom of the issue.  Only after I RDP-ed into the new instance, the abovementioned Parsec Host setting reverted back to ".\\.Display1.\". But still, that did not solve the issue.

Here's some additional info for troubleshooting:
Instance type: g4dn.xlarge
- When I used Parsec client on macOS, I could toggle between 1368x768 and 1280x1024.
- When I used Parsec client on Windows, the resolution did not go beyond 1280x1024 regardless of any higher resolution I forced Parsec to use.

**Comment by keithvassallomt** [comment]
Hi @josiasteo,

Thanks for your kind words.

Honestly, I may be a bit out of my depth here. I'm more of an AWS guy than a Parsec guy, and this seems more like a Parsec/NVIDIA issue to me. As the new instance is created from an image, it should be identical. The only thing I can think of is some hardware ID changing and hence some driver not working as it should, but I'm not well-versed enough in hardware to say for sure.

I haven't had this issue on my AWS build, but I did have something similar on Paperspace, where my native 16:10 resolution was simply ignored by the Parsec host. 

- Can you try re-running the GPU updater on the host? Perhaps that would fix the problem.

- Are you using Server 2016 or 2019?

- Using the NVIDIA control panel, are you able to switch to the desired resolution?

Just trying to figure out whether the problem you have is the same one I had on Paperspace. In my case the problem was on of aspect ratio which I had partially solved by following https://support.parsecgaming.com/hc/en-us/articles/360001331832-Adding-Non-Standard-Aspect-Ratios-To-Your-Cloud-PC

Let me know.

**Comment by josiasteo** [comment]
Hi Keith,

I will re-run the GPU Updater and update you on the result.

I’m using Server 2016 Base.

I took a swing at Nvidia Control Panel, and tried to specify a custom resolution on the one and only display I saw (NVIDIA GVFX), but the button to specify a custom resolution was greyed out, and I couldn’t click on it.  I will try to snoop around for any possible Nvidia Control Panel config file and see if I can update that file directly.

Cheers,
Josias Teo

**Comment by josiasteo** [comment]
Hi Keith,

While re-running GPU Updater, I had to fix a couple of bugs in the process. Still, it did not work.

Is there any difference between doing the whole setup on Server 2016 or 2019?  Perhaps I’ll try out the entire setup on 2019 and see if that solves the problem.

Regarding your last comment on the aspect ratio problem for Paperspace, trying to specify a custom resolution on a g4dn isn’t allowed.  I followed the instructions to locate the place on the Nvidia Control Panel to specify custom resolutions, but there wasn’t even a default entry for me to edit and I couldn’t create new resolutions either.

Cheers,
Josias Teo

**Comment by keithvassallomt** [comment]
I actually figured it out after I had the problem myself.

When you launch the instance the first time, make it on-demand, i.e. not spot. Do all the installations as necessary, including GPU updater, the script etc. When creating the launch configuration, DO make it a spot instance. After you're done with the instance and after you confirm that after a restart everything is working, only then should you shutdown the machine.

Subsequent runs will be spot instances, but with working configuration.

**Comment by josiasteo** [comment]
Perfect! This worked. Thank you. Also, there is no difference between Server 2016 or 2019. Both worked equally well.


Cheers,
Josias Teo

**Comment by mcapacch** [comment]
Hi there,

I came here searching for exactly this issue and I just wanted to point out that there's nothing wrong with your tutorial (which is amazing btw) and this worked for me:
https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/issues/18#issuecomment-631844137

keep gaming,
cheers!
Cap
