### ISSUE TITLE
multiple snapshots are created 

### ISSUE THREAD

**Issue by mme89** [keithvassallomt/parsec-aws-automation#7]
hi,
first of all, thank you very much for the great tutorial and the work you put in here.

So everything's works like it should, also the automation script is working.
The only thing I noticed, is that there are 3 Snapshots being created. Did I miss something following your tutorial?

<img width="1338" alt="Bildschirmfoto 2021-05-15 um 23 15 47" src="https://user-images.githubusercontent.com/20055295/118378350-8d670d00-b5d3-11eb-8e48-974683ff70a8.png">

thanks[](url)

**Comment by keithvassallomt** [comment]
The script must be timing out. If you've made many changes to the disk (such as installing a large game), the snapshot may take longer than 15 minutes to be created. Since Lambda is only allowed to run for 15 minutes max, this causes problems. I would suggest creating a manual snapshot when you install a game, and leave the automation for after normal gaming sessions. 

Another thing you may try to improve performance is change the disk type to gp3 with 16,000 IOPS and 1000Mbps throughput - you can do this from the launch template.

**Comment by mme89** [comment]
Thanks, that makes sense.

And already noticed, that the gp2 volumes are pretty slow.
